In [30]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import folium

In [31]:
import pandas as pd

pd.set_option('display.max_rows', None)  # show all rows
pd.set_option('display.max_columns', None)  # show all columns

df = pd.read_csv("data/train_master.csv")
df  # now all rows will be displayed


barangay  population  land_area_km2  latitude  longitude  \
0         Agusan       18485           6.28   8.48524  124.74900   
1      Baikingon        2930           5.57   8.46568  124.57111   
2        Balubal        6700          15.94   8.45186  124.77715   
3       Balulang       43315           7.19   8.44131  124.62700   
4     Barangay 1         180           0.09   8.47524  124.64269   
5     Barangay 2          60           0.04   8.47629  124.64251   
6     Barangay 3         110        2542.00   8.47616  124.64526   
7     Barangay 4          80        1296.00   8.47674  124.64341   
8     Barangay 5          50         984.80   8.47745  124.64374   
9     Barangay 6          40           0.04   8.47766  124.64141   
10    Barangay 7         560           0.07   8.47951  124.64179   
11    Barangay 8         100           0.03   8.47869  124.64347   
12    Barangay 9         140           0.03   8.47821  124.64516   
13   Barangay 10         570           0.05   8.48108  124.64195   
14   Barangay 11         170           0.03   8.48009  124.64395   
15   Barangay 12         265           0.02   8.47935  124.64549   
16   Barangay 13         960           0.10   8.48281  124.64221   
17   Barangay 14         360           0.05   8.48210  124.64467   
18   Barangay 15        1840           0.12   8.48493  124.64277   
19   Barangay 16          30           0.02   8.48364  124.64551   
20   Barangay 17        2045           0.10   8.48687  124.64324   
21   Barangay 18        1300           0.05   8.48597  124.64548   
22   Barangay 19         250           0.02   8.48470  124.64635   
23   Barangay 20          84           0.02   8.48585  124.64716   
24   Barangay 21         366           0.04   8.49148  124.65182   
25   Barangay 22        3260           0.18   8.48922  124.65365   
26   Barangay 23         948           0.08   8.48981  124.65074   
27   Barangay 24         624           0.17   8.48453  124.65306   
28   Barangay 25         650           0.14   8.48780  124.64901   
29   Barangay 26        1205           0.09   8.48633  124.65279   
30   Barangay 27        1648           0.13   8.48472  124.64898   
31   Barangay 28         510           0.08   8.48133  124.65207   
32   Barangay 29         486           0.19   8.48130  124.64729   
33   Barangay 30         678           0.06   8.48094  124.64992   
34   Barangay 31         586           0.27   8.48067  124.65511   
35   Barangay 32         777           0.08   8.47856  124.64911   
36   Barangay 33          87           0.06   8.47812  124.65138   
37   Barangay 34         540           0.03   8.47778  124.65295   
38   Barangay 35        1989           0.04   8.47782  124.65464   
39   Barangay 36         440           0.06   8.47609  124.65506   
40   Barangay 37         178           0.03   8.47609  124.65308   
41   Barangay 38          50           0.04   8.47627  124.65103   
42   Barangay 39          20           0.02   8.47659  124.64945   
43   Barangay 40         335           0.16   8.47596  124.64756   
44       Bayabas       13720           2.00   8.51094  124.63731   
45       Bayanga        3370          25.16   8.35527  124.58015   
46       Besigan        1714          24.23   8.26013  124.55889   
47        Bonbon       10788           0.80   8.50825  124.64819   
48          Bugo       30320          11.24   8.50057  124.78156   
49         Bulua       34520           6.59   8.50316  124.61231   
50    Camaman-an       36148           3.21   8.46957  124.65971   
51      Canitoan       33816           9.40   8.46207  124.60019   
52        Carmen       79404           7.88   8.47880  124.62912   
53   Consolacion        9648           0.51   8.49084  124.64675   
54        Cugman       22774          16.00   8.45191  124.69171   
55    Dansolihon        6179          42.44   8.30905  124.58349   
56  F.S Catanico        2380          15.86   8.43906  124.72349   
57          Gusa       28810           4.56   8.46870  124.68294

In [37]:
def classify_severity(density):
    if density < 3000:
        return "Low"
    elif density < 5000:
        return "Moderate"
    else:
        return "Severe"

months = ["jun","jul","aug","sep","oct","nov"]

for m in months:
    df[f"{m}_severity"] = df[f"{m}_density"].apply(classify_severity)

In [38]:
density_cols = [f"{m}_density" for m in months[:-1]]  # Jun → Oct
df[density_cols] = df[density_cols] * np.random.normal(1, 0.05, df[density_cols].shape)

In [42]:
# Use population, land area, latitude, longitude + last 3 months as features
feature_cols = ["population","land_area_km2","latitude","longitude",
                "aug_density","sep_density","oct_density"]

X_train = df[feature_cols]
y_train = df["nov_severity"]

In [43]:
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=2, min_samples_split=5,
                       random_state=42)

In [44]:
y_pred = model.predict(X_train)
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_pred))
print("\nClassification Report:")
print(classification_report(y_train, y_pred))

Confusion Matrix:
[[50  0  0]
 [ 0 17  0]
 [ 0  0 13]]

Classification Report:
              precision    recall  f1-score   support

         Low       1.00      1.00      1.00        50
    Moderate       1.00      1.00      1.00        17
      Severe       1.00      1.00      1.00        13

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80



In [45]:
# Prepare December features
feature_cols = ["population","land_area_km2","latitude","longitude",
                "aug_density","sep_density","oct_density"]
X_dec = df[feature_cols].copy()

# Predict severity (Low / Moderate / Severe) using trained Random Forest
df["dec_predicted_severity"] = model.predict(X_dec)

# Save December predictions
df[["barangay", "dec_density", "dec_predicted_severity"]].to_csv(
    "data/december_predictions.csv", index=False
)

In [49]:
severity_colors = {
    "Low": "green",
    "Moderate": "orange",
    "Severe": "red"
}

m = folium.Map(location=[8.482, 124.647], zoom_start=12)

for _, row in df.iterrows():
    severity = row["dec_predicted_severity"]
    color = severity_colors.get(severity, "gray")
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=8,
        color=color,
        fill=True,
        fill_opacity=0.7,
        popup=f"{row['barangay']} - {severity}").add_to(m)

m


In [50]:
import joblib
joblib.dump(model, "rf_hotspot.pkl")


['rf_hotspot.pkl']

In [27]:
m = folium.Map(location=[8.48, 124.65], zoom_start=12)
m.save("default_map.html")